In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("table-dzfd.csv")

df

,region,tdate,country,discharging_port,delivery_mode,customer_name,customer_group,category,pid,pallets,...,storage_cost3,jours_half,jours_1,jours_2,jours_3,ac_status,contract_id,contract_status,invoice,Payment_status
0,region,2003-11-11,morocco,casa,transport,ana,ana,mcp,213,1 pallet per BB,...,0,0,0,0,0,NaN,0,NaN,0,Paid
1,ldsnjs,1111-11-11,dsf,jtf,yg,ligy,li,ug,0,iug,...,0,0,0,0,0,NaN,0,NaN,0,Not Paid
2,ldsnjs,1111-11-11,dsf,jtf,yg,ligy,li,ug,0,iug,...,0,0,0,0,0,NaN,0,NaN,0,Not Paid

In [10]:
df.to_excel("table.xlsx")